x86/apic: Use common library outb() implementation
Remove the redundant local outb() implementation in favour of using the
common outb() implementation defined in lib/x86/asm/io.h, and convert
set_irq_line() to not open-code the out instruction.

Verfied no changes in assembly output for all three callsites, tested,
no functional changes were observed.

The rationale behind this change is that, support for SNP tests that are
introduced later will need apic sources to include common library io
code and if we don't remove apic's local outb() implementation, then we
get the following compilation conflicts:

In file included from lib/x86/apic.c:7:
lib/x86/asm/io.h:30:14: error: conflicting types for ‘outb’; have ‘void(unsigned char,  short unsigned int)’
   30 | #define outb outb
      |              ^~~~

Signed-off-by: Pavan Kumar Paluri <papaluri@amd.com>